const directionData = [
    {
      name: 'Before meals',
      code: 'before_meals',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 1,
    },
    {
      name: 'After meals',
      code: 'after_meals',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 2,
    },
    {
      name: 'With meals',
      code: 'with_meals',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 3,
    },
    {
      name: 'Before breakfast',
      code: 'before_breakfast',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 4,
    },
    {
      name: 'After breakfast',
      code: 'after_breakfast',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 5,
    },
    {
      name: 'Before lunch',
      code: 'before_lunch',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 6,
    },
    {
      name: 'After lunch',
      code: 'after_lunch',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 7,
    },
    {
      name: 'Before dinner',
      code: 'before_dinner',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 8,
    },
    {
      name: 'After dinner',
      code: 'after_dinner',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 9,
    },
    {
      name: 'Before bedtime',
      code: 'before_bedtime',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 10,
    },
    {
      name: 'At bedtime',
      code: 'at_bedtime',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 11,
    },
    {
      name: 'At wake-up',
      code: 'at_wake_up',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 12,
    },
    {
      name: 'In the morning',
      code: 'in_the_morning',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 13,
    },
    {
      name: 'In the afternoon',
      code: 'in_the_afternoon',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 14,
    },
    {
      name: 'In the evening',
      code: 'in_the_evening',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 15,
    },
    {
      name: 'With a meal or snack',
      code: 'with_a_meal_or_snack',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 16,
    },
    {
      name: 'Without food',
      code: 'without_food',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 17,
    },
    {
      name: 'With a full glass of water',
      code: 'with_a_full_glass_of_water',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 18,
    },
    {
      name: 'Other (please specify)',
      code: 'Other_direction_type',
      description: '',
      globalCategoryTypeCode: 'direction_type',
      isDeleted: false,
      isActive: true,
      sortOrder: 19,
    },

  ];
  
  module.exports = {
    directionData,
  };
  