const doseFormData = [
  {
    name: 'Applicator',
    code: 'applicator',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 1,

  },
  {
    name: 'Blister',
    code: 'blister',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 2,

  },
  {
    name: 'Caplet',
    code: 'caplet',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Capsule',
    code: 'capsule',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Cream',
    code: 'cream',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Each',
    code: 'each',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Film',
    code: 'film',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Gel',
    code: 'gel',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'Gram',
    code: 'gram',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'Gum',
    code: 'gum',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Implant',
    code: 'implant',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'Insert',
    code: 'insert',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Kit Lancet',
    code: 'kit_lancet',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Liquid',
    code: 'liquid',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: 'Lozenge',
    code: 'lozenge',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 15,
  },
  {
    name: 'Milliliter',
    code: 'milliliter',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 16,
  },
  {
    name: 'Ointment',
    code: 'ointment',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    name: 'Packet',
    code: 'packet',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 18,
  },
  {
    name: 'Pad',
    code: 'pad',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 19,
  },
  {
    name: 'Patch',
    code: 'patch',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 20,
  },  {
    name: 'Pen',
    code: 'pen',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 21,
  },
  {
    name: 'Needle',
    code: 'needle',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 22,
  },
  {
    name: 'Ring',
    code: 'ring',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 23,
  },
  {
    name: 'Sponge',
    code: 'sponge',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 24,
  },
  {
    name: 'Stick',
    code: 'stick',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 25,
  },
  {
    name: 'Strip',
    code: 'strip',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 26,
  },
  {
    name: 'Suppository',
    code: 'suppository',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 27,
  },
  {
    name: 'Swab',
    code: 'swab',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 28,
  },
  {
    name: 'Tablet',
    code: 'tablet',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 29,
  },
  {
    name: 'Troche',
    code: 'troche',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 30,
  },
  {
    name: 'Wafer',
    code: 'wafer',
    description: '',
    globalCategoryTypeCode: 'dose_form_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 31,
  },
];

module.exports = {
  doseFormData,
};
