const emailType = [
  {
    name: 'Appointment Create',
    code: 'appointment_create',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Start Date', token: 'startDate' },
      { label: 'Start Time', token: 'startTime' },
      { label: 'End Time', token: 'endTime' },
      { label: 'Practioner First Name', token: 'practionerFirstName' },
      { label: 'Practioner Middle Name', token: 'practionerMiddleName' },
      { label: 'Practioner Last Name', token: 'practionerLastName' },
      { label: 'Appointment Type', token: 'appointmentType' },
      { label: 'Meeting Link', token: 'meetingLink' },
      { label: 'Location', token: 'location' },
      { label: 'Client Logo', token: 'logo' },
      { label: 'Client Url', token: 'clientURL' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Appointment Recurring',
    code: 'appointment_recurring',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Start Time', token: 'startTime' },
      { label: 'End Time', token: 'endTime' },
      { label: 'Practioner First Name', token: 'practionerFirstName' },
      { label: 'Practioner Middle Name', token: 'practionerMiddleName' },
      { label: 'Practioner Last Name', token: 'practionerLastName' },
      { label: 'Location', token: 'location' },
      { label: 'Recurring Summary', token: 'recurringSummary' },
      { label: 'Appointment Type', token: 'appointmentType' },
      { label: 'Meeting Link', token: 'meetingLink' },
      { label: 'Client Logo', token: 'logo' },
      { label: 'Client Url', token: 'clientURL' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Appointment Reminder',
    code: 'appointment_reminder',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Start Date', token: 'startDate' },
      { label: 'Start Time', token: 'startTime' },
      { label: 'Meeting Link', token: 'meetingLink' },
      { label: 'Client Logo', token: 'logo' },
      { label: 'Client Url', token: 'clientURL' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Appointment Reschedule',
    code: 'appointment_reschedule',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Start Date', token: 'startDate' },
      { label: 'Start Time', token: 'startTime' },
      { label: 'End Time', token: 'endTime' },
      { label: 'Previous End Time', token: 'previousEndTime' },
      { label: 'Previous Start Date', token: 'previousStartDate' },
      { label: 'Previous Start Time', token: 'previousStartTime' },
      { label: 'Practioner First Name', token: 'practionerFirstName' },
      { label: 'Practioner Middle Name', token: 'practionerMiddleName' },
      { label: 'Practioner Last Name', token: 'practionerLastName' },
      { label: 'Meeting Link', token: 'meetingLink' },
      { label: 'Client Logo', token: 'logo' },
      { label: 'Client Url', token: 'clientURL' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Recurring Appointment Reschedule',
    code: 'recurring_appointment_reschedule',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Start Time', token: 'startTime' },
      { label: 'End Time', token: 'endTime' },
      { label: 'Previous End Time', token: 'previousEndTime' },
      { label: 'Previous Start Time', token: 'previousStartTime' },
      { label: 'Practioner First Name', token: 'practionerFirstName' },
      { label: 'Practioner Middle Name', token: 'practionerMiddleName' },
      { label: 'Practioner Last Name', token: 'practionerLastName' },
      { label: 'Recurring Summary', token: 'recurringSummary' },
      { label: 'Old Recurring Summary', token: 'previousRecurringSummary' },
      { label: 'Meeting Link', token: 'meetingLink' },
      { label: 'Client Logo', token: 'logo' },
      { label: 'Client Url', token: 'clientURL' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Appointment Confirmed ',
    code: 'appointment_approved',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Start Date', token: 'startDate' },
      { label: 'Start Time', token: 'startTime' },
      { label: 'End Time', token: 'endTime' },
      { label: 'Practioner First Name', token: 'practionerFirstName' },
      { label: 'Practioner Middle Name', token: 'practionerMiddleName' },
      { label: 'Practioner Last Name', token: 'practionerLastName' },
      { label: 'Appointment Type', token: 'appointmentType' },
      { label: 'Meeting Link', token: 'meetingLink' },
      { label: 'Location', token: 'location' },
      { label: 'Client Logo', token: 'logo' },
      { label: 'Client Url', token: 'clientURL' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Appointment Rejected',
    code: 'appointment_rejected',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Start Date', token: 'startDate' },
      { label: 'Start Time', token: 'startTime' },
      { label: 'End Time', token: 'endTime' },
      { label: 'Practioner First Name', token: 'practionerFirstName' },
      { label: 'Practioner Middle Name', token: 'practionerMiddleName' },
      { label: 'Practioner Last Name', token: 'practionerLastName' },
      { label: 'Appointment Type', token: 'appointmentType' },
      { label: 'Location', token: 'location' },
      { label: 'Meeting Link', token: 'meetingLink' },
      { label: 'Client Logo', token: 'logo' },
      { label: 'Client Url', token: 'clientURL' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Prescription',
    code: 'prescription',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Start Date', token: 'startDate' },
      { label: 'End Date', token: 'endDate' },
      { label: 'Start Time', token: 'startTime' },
      { label: 'End Time', token: 'endTime' },
      { label: 'Prescriber First Name', token: 'prescriberFirstName' },
      { label: 'Prescriber Middle Name', token: 'prescriberMiddleName' },
      { label: 'Prescriber Last Name', token: 'prescriberLastName' },
      { label: 'Client Logo', token: 'logo' },
      { label: 'Client Url', token: 'clientURL' },
      { label: 'Prescriber Url', token: 'prescriberUrl' },
      { label: 'Form Url', token: 'formUrl' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'Reset Password',
    code: 'reset_password',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Client Url', token: 'clientURL' },
      { label: 'Client Logo', token: 'logo' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'Forget Password',
    code: 'forget_password',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'RESET URL', token: 'resetURL' },
      { label: 'Client Url', token: 'clientURL' },
      { label: 'Client Logo', token: 'logo' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Patient Create',
    code: 'patient_create',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Client Logo', token: 'logo' },
      { label: 'Patient Email', token: 'patientEmail' },
      { label: 'Patient Password', token: 'patientPassword' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'Staff Create',
    code: 'staff_create',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Client Logo', token: 'logo' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Birthday',
    code: 'birthday',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Patient Middle Name', token: 'patientMiddleName' },
      { label: 'Patient Last Name', token: 'patientLastName' },
      { label: 'Client Logo', token: 'logo' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Generate Password',
    code: 'generate_password',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Patient First Name', token: 'patientFirstName' },
      { label: 'Client Url', token: 'clientURL' },
      { label: 'Client Logo', token: 'logo' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: 'Subscription Cancelled',
    code: 'subscription_cancelled',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Clinic Name', token: 'clinicName' },
      { label: 'Start Date', token: 'startDate' },
      { label: 'End Date', token: 'endDate' },
      { label: 'Is Clinic Admin', token: 'isClinicAdmin' },
      { label: 'Practition Count', token: 'practitionerCount' },
      { label: 'Rn Count', token: 'rnCount' },
      { label: 'Prescriber Count', token: 'prescriberCount' },
      { label: 'Clinic Admin Message', token: 'clinicAdminMessage' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 15,
  },
  {
    name: 'Subscription Deactivated',
    code: 'subscription_deactivated',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Clinic Name', token: 'clinicName' },
      { label: 'Start Date', token: 'startDate' },
      { label: 'End Date', token: 'endDate' },
      { label: 'Is Clinic Admin', token: 'isClinicAdmin' },
      { label: 'Practition Count', token: 'practitionerCount' },
      { label: 'Rn Count', token: 'rnCount' },
      { label: 'Prescriber Count', token: 'prescriberCount' },
      { label: 'Clinic Admin Message', token: 'clinicAdminMessage' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 16,
  },
  {
    name: 'Failed Login',
    code: 'failed_login',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Client Logo', token: 'logo' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    name: 'Trial Expiry Reminder',
    code: 'trial_expiry_reminder',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Clinic Name', token: 'clinicName' },
      { label: 'Start Date', token: 'startDate' },
      { label: 'End Date', token: 'endDate' },
      { label: 'Days Left', token: 'daysLeft' },
      { label: 'Clinic Admin Message', token: 'clinicAdminMessage' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 18,
  },
   {
    name: 'Subscription Renewal',
    code: 'subscription_renewal',
    description: '',
    globalCategoryTypeCode: 'email_type_code',
    metaData: [
      { label: 'Clinic Name', token: 'clinicName' },
    ],
    isDeleted: false,
    isActive: true,
    sortOrder: 19,
  },
];
module.exports = {
  emailType,
};
