const encounterType = [
   {
    name: 'DAP',
    code: 'dap',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'BIRP',
    code: 'birp',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'H & P',
    code: 'hp_encounter_type',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Amendment',
    code: 'amendment',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Amendment to Encounter',
    code: 'amendment_to_encounter',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Contraception Visit',
    code: 'contraception_visit',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Fetal Echocardiography ',
    code: 'fetal_echocardiography ',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Fetal Medicine Evaluation',
    code: 'fetal_medicine_evaluation',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'Fetal MRI',
    code: 'fetal_mri',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'Fetal Procedure ',
    code: 'fetal_procedure ',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Fetal Ultrasound ',
    code: 'fetal_ultrasound ',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'General Obstetric Evaluation ',
    code: 'general_obstetric_evaluation ',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Group',
    code: 'group_encounter_type',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Gynecology Visit',
    code: 'gynecology_visit',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: 'Infertility Visit',
    code: 'infertility_visit',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 15,
  },
  {
    name: 'Maternal Medicine Evaluation',
    code: 'maternal_medicine_evaluation',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 16,
  },
  {
    name: 'Memo to Record',
    code: 'memo_to_record',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    name: 'Nurse Visit',
    code: 'nurse_visit',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 18,
  },
  {
    name: 'Phone',
    code: 'phone_encounter_type',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 19,
  },
  {
    name: 'Physical Therapy Discharge Summary',
    code: 'physical_therapy_discharge_summary',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 20,
  },
  {
    name: 'Physical Therapy Initial Evaluation',
    code: 'physical_therapy_initial_evaluation',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 21,
  },
  {
    name: 'Physical Therapy Interim',
    code: 'physical_therapy_interim',
    globalCategoryTypeCode: 'encounter_types_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 22,
  },
];
module.exports = {
  encounterType,
};
