const familyCondition = [
  {
    name: 'Anemia',
    code: 'anemia',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Asthma/respiratory problems',
    code: 'asthma_respiratory_problems',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Cancer (type)',
    code: 'cancer_type',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Chronic Fatigue',
    code: 'chronic_fatigue',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Chronic Pain',
    code: 'chronic_pain',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Diabetes',
    code: 'diabetes',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Epilepsy or seizures',
    code: 'epilepsy_seizures',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Fibromyalgia',
    code: 'fibromyalgia',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'Head trauma/ Traumatic Brain Injury',
    code: 'head_trauma_tbi',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'Heart Disease',
    code: 'heart_disease',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'High blood pressure',
    code: 'high_blood_pressure',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'High cholesterol',
    code: 'high_cholesterol',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Intellectual or Developmental Disability',
    code: 'intellectual_developmental_disability',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Kidney Disease',
    code: 'kidney_disease',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: 'Liver Disease/ problems',
    code: 'liver_disease_problems',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 15,
  },
  {
    name: 'Stomach or intestinal problems',
    code: 'stomach_intestinal_problems',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 16,
  },
  {
    name: 'Thyroid Disease',
    code: 'thyroid_disease',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    name: 'Stroke',
    code: 'stroke',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 18,
  },
  {
    name: 'Headache/Migraines',
    code: 'headache_migraines',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 19,
  },
  {
    name: 'HIV/AIDS',
    code: 'hiv_aids',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 20,
  },
  {
    name: 'Other (please specify)',
    code: 'family_condition_other',
    description: '',
    globalCategoryTypeCode: 'family_condition',
    isDeleted: false,
    isActive: true,
    sortOrder: 21,
  },
];

module.exports = {
  familyCondition,
};
