const frequencyData = [
  {
    name: 'Once daily (QD or OD)',
    code: 'once_daily',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Twice daily (BID)',
    code: 'twice_daily',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Three times daily (TID)',
    code: 'three_times_daily',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Four times daily (QID)',
    code: 'four_times_daily',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Every 6 hours (Q6H)',
    code: 'every_6_hours',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Every 8 hours (Q8H)',
    code: 'every_8_hours',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Every 12 hours (Q12H)',
    code: 'every_12_hours',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Every morning (QAM)',
    code: 'every_morning',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'Every evening (QPM)',
    code: 'every_evening',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'Every night (QHS)',
    code: 'every_night',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Every other day (QOD)',
    code: 'every_other_day',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'Every week (QW)',
    code: 'every_week',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Every month (QM)',
    code: 'every_month',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Every year (QY)',
    code: 'every_year',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: 'Every hour',
    code: 'every_hour',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 15,
  },
  {
    name: 'As needed (PRN)',
    code: 'as_needed',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 16,
  },
  {
    name: 'Continuous',
    code: 'continuous',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    name: 'Other (please specify)',
    code: 'other_frequency_type',
    description: '',
    globalCategoryTypeCode: 'frequency_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 18,
  },

];

module.exports = {
  frequencyData,
};
