const genders = [
  {
    name: 'Prefer not to disclose',
    code: 'prefer_not_to_disclose_gender',
    description: '',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:8,
  },
  {
    name: 'Male',
    code: 'male',
    description: 'Male',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:1,
  },
  {
    name: 'Female',
    code: 'female',
    description: '',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:2,
  },
  {
    name: 'Transgender Male',
    code: 'transgender_male',
    description: 'Female-to-male/Trans Male',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:3
  },
  {
    name: 'Transgender Female',
    code: 'transgender_female',
    description: 'Male-to female/Trans Female',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:4,
  },
  {
    name: 'Agender',
    code: 'agender',
    description: 'Identifies as having no gender or as being without a specific gender identity',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:5,
  },
  {
    name: 'Cisgender',
    code: 'cisgender',
    description:
      'individuals whose gender identity aligns with the sex they were assigned at birth, such as someone who was assigned male at birth and identifies as a man or someone who was assigned female at birth and identifies as a woman',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:6,
  },
  {
    name: 'Genderqueer',
    code: 'genderqueer',
    description:
      'gender identity is not exclusively male or female, and may include a combination of both, neither, or a different gender altogether',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:7,
  },
  {
    name: 'Unknown',
    code: 'unknown_gender',
    description: '',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:9,
  },
  {
    name: 'Another gender identity',
    code: 'another_gender_identity',
    description: 'please specify',
    globalCategoryTypeCode: 'gender',
    isDeleted: false,
    isActive: true,
    sortOrder:10,
  },
];
module.exports = {
  genders,
};
