const GlobalTypeCategoryData = [
  {
    name: 'Gender',
    code: 'gender',
    description: 'Gender List',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Gender At Birth',
    code: 'gender_at_birth',
    description: 'Gender List',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Name PreFixes',
    code: 'name_prefixes',
    description: 'Name Prefixes List',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Appointment Type',
    code: 'appointment_type',
    description: 'Appointment Type',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Encounters',
    code: 'encounters',
    description: 'Patient Encounters',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Insurance Policy Holder',
    code: 'insurance_policy_holder',
    description: 'Insurance Policy Holder',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Marital Status',
    code: 'marital_status',
    description: 'Marital Status',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Pronouns',
    code: 'pronouns',
    description: 'Pronouns',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Sexual Orientation',
    code: 'sexual_orientation',
    description: 'Sexual Orientation',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Allergy Reactions',
    code: 'allergy_reactions',
    description: 'Allergy Reactions',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Allergy Severities',
    code: 'allergy_severities',
    description: 'Allergy Severities',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Diagnosis Type',
    code: 'diagnosis_type',
    description: 'Diagnosis Type',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Diagnosis Status',
    code: 'diagnosis_status',
    description: 'Diagnosis Status',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Status Code',
    code: 'status_code',
    description: 'Status Code',
    isDeleted: false,
    isActive: true,
    isColorCode:true,
  },
  {
    name: 'Form Types',
    code: 'form_type',
    description: 'Form Types',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Form Category',
    code: 'form_category',
    description: 'Form Categories',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Family Relation',
    code: 'family_relation',
    description: 'Family Relation',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Dose Types',
    code: 'dose_type',
    description: 'Dose Types',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Dose Form Types',
    code: 'dose_form_type',
    description: 'Dose Form Types',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Family Condition',
    code: 'family_condition',
    description: 'Family Condition',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Unit Types',
    code: 'unit_type',
    description: 'Unit Types',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Race Code',
    code: 'race_code',
    description: 'Race Code',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Route Types',
    code: 'route_type',
    description: 'Route Types',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Religions',
    code: 'religions',
    description: 'Religions',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Frequency Types',
    code: 'frequency_type',
    description: 'Frequency Types',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Occupations',
    code: 'occupations',
    description: 'Occupations',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Direction Types',
    code: 'direction_type',
    description: 'Direction Types',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Financial Responsibility Party',
    code: 'financial_responsibility_party',
    description: 'financial responsibility party',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Social History',
    code: 'social_history_code',
    description: 'Social History',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Duration Types',
    code: 'duration_type',
    description: 'Duration Types',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Preferred Contact Methods',
    code: 'contact_methods',
    description: 'Preferred Contact Methods',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Appointment Status',
    code: 'appointment_status',
    description: '',
    isDeleted: false,
    isActive: true,
    isColorCode:true,
  },
  {
    name: 'Appointment Copay',
    code: 'appointment_copay',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'HL7 Versions',
    code: 'hl7_versions',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Speciment Types',
    code: 'specimen_types_code',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Email Types',
    code: 'email_type_code',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  { name: 'Encounter Types',
    code: 'encounter_types_code',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  { name: 'SOAP Note Template',
    code: 'soap_note_template',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Emergency Contact Relation',
    code: 'emergency_contact_relation',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  { name: 'Billing Types',
    code: 'billing_type',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  { name: 'Billing Status',
    code: 'billing_status',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Treatment Plan Status',
    code: 'treatment_plan_status',
    description: 'Treatment Plan Status',
    isDeleted: false,
    isActive: true,
    isColorCode:true,
  },
  {
    name: 'Permissions',
    code: 'permissions',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Patient Document Type',
    code: 'patient_document_type',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Medication Actions',
    code: 'medication_actions',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Medication Status',
    code: 'medication_status',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'MAR Log Action',
    code: 'mar_log_action',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  { 
    name: 'Appointment Confirmation',
    code: 'appointment_confirmation',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Appointment Interval',
    code: 'appointment_interval',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Lead Days',
    code: 'lead_days',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Lead Interval',
    code: 'lead_interval',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Erx Status',
    code: 'erx_status',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Homework Status',
    code: 'homework_status',
    description: '',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'General Claim Status',
    code: 'general_claim_status',
    description: 'General Claim Status',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Treatment Plan Label',
    code: 'treatment_plan_label',
    description: 'Treatment Plan Label',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Subscription Cancel Reason',
    code: 'subsription_cancel_reason',
    description: 'Subscription Cancel Reason',
    isDeleted: false,
    isActive: true,
  },
];

module.exports = GlobalTypeCategoryData;
