const hl7Versions = [
  {
    name: 'HL7 v2.1',
    code: '2.1',
    description: 'Version 2.1 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'HL7 v2.2',
    code: '2.2',
    description: 'Version 2.2 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'HL7 v2.3',
    code: '2.3',
    description: 'Version 2.3 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'HL7 v2.3.1',
    code: '2.3.1',
    description: 'Version 2.3.1 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'HL7 v2.4',
    code: '2.4',
    description: 'Version 2.4 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'HL7 v2.5',
    code: '2.5',
    description: 'Version 2.5 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'HL7 v2.5.1',
    code: '2.5.1',
    description: 'Version 2.5.1 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'HL7 v2.6',
    code: '2.6',
    description: 'Version 2.6 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'HL7 v2.7',
    code: '2.7',
    description: 'Version 2.7 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'HL7 v2.8',
    code: '2.8',
    description: 'Version 2.8 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'HL7 v3',
    code: '3.0',
    description: 'Version 3.0 of HL7 standard',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'HL7 FHIR',
    code: 'fhir',
    description: 'Fast Healthcare Interoperability Resources',
    globalCategoryTypeCode: 'hl7_versions',
    isDeleted: false,
    isActive: true,
    sortOrder: 12,
  },
];
module.exports = {
  hl7Versions,
};
