const leadDays = [
  {
    name: 'Same day',
    code: '0_day',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: '1 day',
    code: '1_day',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: '2 days',
    code: '2_days',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: '3 days',
    code: '3_days',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: '4 days',
    code: '4_day',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: '5 days',
    code: '5_days',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: '6 days',
    code: '6_days',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: '7 days',
    code: '7_days',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: '8 days',
    code: '8_day',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: '9 days',
    code: '9_days',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: '10 days',
    code: '10_days',
    description: '',
    globalCategoryTypeCode: 'lead_days',
    isDeleted: false,
    isActive: true,
    sortOrder: 11,
  },
];
module.exports = {
  leadDays,
};
