const maritalStatus = [
  {
    name: 'Single',
    code: 'single',
    description: '',
    globalCategoryTypeCode: 'marital_status',
    isDeleted: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Married',
    code: 'married',
    description: '',
    globalCategoryTypeCode: 'marital_status',
    isDeleted: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Divorced',
    code: 'divorced',
    description: '',
    globalCategoryTypeCode: 'marital_status',
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Widowed',
    code: 'widowed',
    description: '',
    globalCategoryTypeCode: 'marital_status',
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Separated',
    code: 'separated',
    description: '',
    globalCategoryTypeCode: 'marital_status',
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Cohabiting',
    code: 'cohabiting',
    description: '',
    globalCategoryTypeCode: 'marital_status',
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Partner',
    code: 'partner',
    description: '',
    globalCategoryTypeCode: 'marital_status',
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
  // {
  //   name: 'N/A',
  //   code: 'n/a',
  //   description: 'Child',
  //   globalCategoryTypeCode: 'marital_status',
  //   isDeleted: false,
  //   isActive: true,
  // },
  {
    name: 'Other',
    code: 'marital_status_other',
    description: '',
    globalCategoryTypeCode: 'marital_status',
    isDeleted: false,
    isActive: true,
    sortOrder: 8,
  },
];

module.exports = {
  maritalStatus,
};
