const namePrefixes = [
  {
    name: 'Mr.',
    code: 'mr.',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
    sortOrder:1,
  },
  {
    name: 'Mrs.',
    code: 'mrs.',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
    sortOrder:3,
  },
  {
    name: 'Miss',
    code: 'miss',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
    sortOrder:2,
  },
  {
    name: 'Dr.',
    code: 'dr',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
    sortOrder:4,
  },
  {
    name: 'Ms.',
    code: 'ms',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
    sortOrder:5,
  },
  {
    name: 'Rev',
    code: 'rev',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
    sortOrder:6,
  },
  {
    name: 'Pst',
    code: 'pst',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
    sortOrder:7,
  },
  {
    name: 'Other',
    code: 'name_prefixes_other',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
    sortOrder:8,
  },
  {
    name: 'Dr.',
    code: 'dr',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Ms.',
    code: 'ms',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Rev',
    code: 'rev',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Pst',
    code: 'pst',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
  },
  {
    name: 'Other',
    code: 'name_prefixes_other',
    description: '',
    globalCategoryTypeCode: 'name_prefixes',
    isDeleted: false,
    isActive: true,
  },
];
module.exports = {
  namePrefixes,
};
