const procedureData = [
  {
    name: 'X-Ray',
    cptCode:'71045',
    useForBillingCode: true,
    description: 'Chest X-Ray',
    isActive: true,
    isDeleted: false,
    modifier1: 0,
    modifier2: 0,
    modifier3: 1,
    modifier4: 0,
    price: 150,
    qty: 1,
    total: 150,
    sortOrder: 1,
  },
  {
    name: 'Surgery',
    cptCode:'44950',
    useForBillingCode: true,
    description: 'Appendectomy',
    isActive: true,
    isDeleted: false,
    modifier1: 1,
    modifier2: 0,
    modifier3: 0,
    modifier4: 0,
    price: 2500,
    qty: 1,
    total: 2500,
    sortOrder: 2,
  },
  {
    name: 'Physical Therapy',
    cptCode:'97161',
    useForBillingCode: true,
    description: 'One-hour session',
    isActive: true,
    isDeleted: false,
    modifier1: 0,
    modifier2: 1,
    modifier3: 0,
    modifier4: 0,
    price: 100,
    qty: 1,
    total: 100,
    sortOrder: 3,
  },
  {
    name: 'Laboratory Test',
    cptCode:'85025',
    useForBillingCode: true,
    description: 'Blood Panel',
    isActive: true,
    isDeleted: false,
    modifier1: 0,
    modifier2: 0,
    modifier3: 0,
    modifier4: 1,
    price: 80,
    qty: 1,
    total: 80,
  },
];

module.exports = {
  procedureData,
};
