const raceCode = [
  {
    name: 'Asian',
    code: 'asian',
    description: '',
    globalCategoryTypeCode: 'race_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'African American or Black',
    code: 'african_american_or_black',
    description: '',
    globalCategoryTypeCode: 'race_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Hispanic or Latino',
    code: 'hispanic_or_latino',
    description: '',
    globalCategoryTypeCode: 'race_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'White',
    code: 'white',
    description: '',
    globalCategoryTypeCode: 'race_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Unknown',
    code: 'unknown',
    description: '',
    globalCategoryTypeCode: 'race_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'American Indian or Alaska Native',
    code: 'american_indian_or_alaska_native',
    description: '',
    globalCategoryTypeCode: 'race_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Native Hawaiian or Pacific Islander',
    code: 'native_hawaiian_or_pacific_islander',
    description: '',
    globalCategoryTypeCode: 'race_code',
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
];
module.exports = {
  raceCode,
};
