const routeData = [
  {
    name: 'Oral',
    code: 'oral',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Topical',
    code: 'topical',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Intramuscular (IM)',
    code: 'intramuscular',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Subcutaneous (SubQ)',
    code: 'subcutaneous',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Intravenous (IV)',
    code: 'Intravenous',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Intradermal (ID)',
    code: 'intradermal',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Intrathecal',
    code: 'intrathecal',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Intra-articular',
    code: 'intra_articular',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'Intraosseous',
    code: 'intraosseous',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'Intracardiac',
    code: 'intracardiac',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Rectal',
    code: 'rectal',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'Vaginal',
    code: 'vaginal',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Nasal',
    code: 'nasal',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Ophthalmic',
    code: 'ophthalmic',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: 'Otic',
    code: 'otic',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 15,
  },
  {
    name: 'Inhalation',
    code: 'inhalation',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 16,
  },
  {
    name: 'Sublingual',
    code: 'sublingual',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    name: 'Buccal',
    code: 'buccal',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 18,
  },
  {
    name: 'Transdermal',
    code: 'transdermal',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 19,
  },
  {
    name: 'Intranasal',
    code: 'intranasal',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 20,
  },
  {
    name: 'Other (please specify)',
    code: 'other_route_type',
    description: '',
    globalCategoryTypeCode: 'route_type',
    isDeleted: false,
    isActive: true,
    sortOrder: 21,
  },
 
];

module.exports = {
  routeData,
};
