const { analyticsReportingController } = require('../controllers');

const AUTH_MODULE = {
  globalTypeCategory: 'GLOBAL_TYPE_CATEGORY',
  globalType: 'GLOBAL_TYPE',
  practice: 'PRACTICE',
  patient: 'PATIENT',
  diagnosis: 'DIAGNOSIS',
  diagnosisicd: 'DIAGNOSIS_ICD',
  diagnosisproblem: 'DIAGNOSIS_PROBLEM',
  insurance: 'INSURANCE',
  allergies: 'ALLERGIES',
  chats: 'CHATS',
  familyHistory: 'FAMILY_HISTORY',
  socialHistory: 'SOCIAL_HISTORY',
  medicalHistory: 'MEDICAL_HISTORY',
  vitals: 'VITALS',
  patientDocument: 'PATIENTDOCUMENT',
  patientMedication: 'PATIENTMEDICATION',
  emergencyContact: 'EMERGENCYCONTACT',
  appointment: 'APPOINTMENT',
  genericDrug: 'GENERIC_DRUG',
  brandNameDrug: 'BRAND_NAME_DRUG',
  labsRadiology: 'LABS_RADIOLOGY',
  hl7: 'HL7',
  form: 'FORM',
  patientForm: 'PATIENT_FORM',
  downloadPatientFormPdf: 'DOWNLOAD_PATIENT_FORM_PDF',
  faxContact: 'Fax_CONTACT',
  faxHisotry: 'FAX_HISTORY',
  patientFormSubmission: 'PATIENT_FORM_SUBMISSION',
  allPatientHistory: 'ALL_PATIENT_HISTORY',
  laboratoryTest: 'LABORATORY_TEST',
  testingLab: 'TESTING_LAB',
  patientMedicationHistory: 'PATIENTMEDICATIONHISTORY',
  emailTemplate: 'EMAILTEMPLATE',
  emailComposed: 'EMAILCOMPOSED',
  encounters: 'ENCOUNTERS',
  encounterBilling: 'ENCOUNTERBILLING',
  diagnosisSnomed: 'DIAGNOSISSNOMED',
  procedureCode: 'PROCEDURE_CODE',
  encountersBilling: 'ENCOUNTERSBILLING',
  treatmentPlan: 'TREATMENTPLAN',
  icdProblem: 'ICDPROBLEM',
  problemBehavior: 'PROBLEMbEHAVIOR',
  behaviorGoal: 'BEHAVIORGOAL',
  goalObjective: 'GOALOBJECTIVE',
  objectiveIntervention: 'OBJECTIVEINTERVENTION',
  staff: 'STAFF',
  labReport: 'LABREPORT',
  userDevice: 'USERDEVICE',
  formLibrary: 'FORMLIBRARY',
  medicationSchedule: 'MEDICATION_SCHEDULE',
  patientMAR: 'PATIENT_MAR',
  patientMedicationItemMARLog: 'PATIENT_MEDICATION_ITEM_MAR_LOG',
  calendarSchedule: 'CALENDARSCHEDULE',
  mdToolbox: 'MD_TOOLBOX',
  payerList: 'PAYER_LIST',
  eligibilityCheckHistroy: 'ELIGIBILITY_CHECK_HISTORY',
  mdToolboxConfig: 'MD_TOOLBOX_CONFIG',
  officeAllyConfig: 'OFFICE_ALLY_CONFIG',
  analyticsAndReporting: 'ANALYTICS_AND_REPORTING',
  invoice: 'INVOICE',
  admin: 'ADMIN',
  loginLogs: 'LOGIN_LOGS',
  emailLogs: 'EMAIL_LOGS',
  emailCampaignTemplate: 'EMAILCAMPAIGNTEMPLATE',
  ////////////////////PATIENT PORTAL///////////////////////

  treatmentPlanTemplate: 'TREATMENT_PLAN_TEMPLATE',
  homework: 'HOMEWORK',
  claims: 'CLAIMS',
  clinic: 'CLINIC',
};
const AUTH_ACTION = {
  create: 'create',
  update: 'edit',
  read: 'read',
  share: 'share',
  delete: 'delete',
  print: 'print',
};

module.exports = {
  AUTH_MODULE,
  AUTH_ACTION,
};
