const errorMessages = {
  CONTENT_TYPE: 'Invalid content type.',
  EMAIL_EXISTS: 'Email already exists.',
  ROLE_REQUIRED: 'Role is required.',
  INVALID_PASSWORD_PATTERN:
    'Password must contain at least one lowercase letter, one uppercase letter, one digit, one special character, and has a minimum length of 8 characters.',
    NOT_FOUND: 'Not Found.',
    INFO_MISSING: 'Some Informations Are Missing.',
    NO_RECORD_FOUND: 'No record found.',
  USER_NOT_FOUND: 'User not found.',
  TOKEN_NOT_FOUND: 'Token not found.',
  FAILED_TO_CREATE: 'Failed to create record.',
  INCOMPLETE_PARAMS: 'Incomplete parameters.',
  EMAIL_VERIFICATION_FAILED: 'Email verification failed.',
  PASSWORD_RESET_FAILED: 'Password reset failed.',
  REQUIRE_AUTHENTICATION: 'Please authenticate.',
  INCORRECT_LOGIN: 'Incorrect email or password.',
  USER_INACTIVE: 'User is inactive.',
  REQUIRE_PRACTICE_FOR_LOCATION: 'Practice must be mandatory for location.',
  DUPLICATE_RECORD: 'Record already exists.',
  INVALID: (key) => `Invalid ${key}.`,
  NOT_AUTHORIZED: 'Not authorized',
  MAX_DAYS_INTERVAL: 'Interval greater then 31 days is not allowd',
  PLEASE_AUTHENTICATE: 'Please authenticate',
  NO_UNIQUE_FILED: 'Unique field not found in record',
  CONSULTATION_REQUIRED: 'Service or consultation expiry is required for consultation',
  _NOT_FOUND: (key) => `${key} not found`,
  PATIENT_SIGNATURE_NOT_ALLOWED: 'Patient Signature Not Allowed',
  PATIENT_SIGNATURE_REQUIRED: 'Patient Signature Required',
  ASSISTANT_SIGNATURE_NOT_ALLOWED: 'Assistant Signature Not Allowed',
  PRACTITIONER_SIGNATURE_NOT_ALLOWED: 'Practitioner Signature Not Allowed',
  ALREADY_SIGNED_BY: (role) => `Already Signed By ${role}`,
  REQUIRED: (value) => `${value} required`,
  ALREADY_SUBMITTED: 'Already Submitted',
  APPOINTMENT_ALREADY_EXISTS: 'Appointment for same date and time already exists',
  OPENTOK_AUTHENTICATION_FAILED: 'OpenTok authentication failed',
  CANCELLATION_NOT_ALLOWED: 'Cancellation not allowed',
  RESCHEDULE_NOT_ALLOWED: 'Reschedule not allowed',
  SAME_RECORD_IS_BEIGN_UPDATED: 'Same record is already being updated',
  GOOGLE_MEET_AUTHENTICATION_FAILED: 'Google Meet Authentication Failed',
  PRACTICE_SETTING_ALREADY_EXISTS: 'Practice setting for same type already exists',
  APPOINTMENT_NOT_ALLOWED_FOR: (status) => `Appointment not allowed for ${status}`,
  INCOMPLETE_OR_INVALID_ADDRESS: `Please fill your local address, we don't ship internationally.`,
  FAILED_TO_DELETE: 'Failed to delete record.',
  INVALID_TOKEN: 'Invalid token',
  VALID_TOKEN: 'Token is valid',
  EMAIL_TYPE_EXIST: 'Template for this email type is already exists.',
  SIGNATURE_REQUIRED: 'Signature required', 
  CHAT_CHANNEL_EXIST: 'Chat for this channel is already exists.',
  CHAT_NOT_EXIST: 'Chat not found! Please try again.',
  PRACTICE_EMAIL_NAME_EXISTS: 'Practice with the same email,name or domain already exists',
  PERMISSION_DENIED: 'You do not have permission to this module.',
  INVALID_OR_EXPIRE_CODE: 'Invalid or expired code', 
  NO_INSURANCE_EXISTS: 'No insurance exists for this insurance type',
  SUBSCRIPTION_INACTIVE: 'Your practice subscription is currently inactive. Please activate it to continue accessing services.',
  SUBSSCRIPTION_CANCELED: ' Your subscription has been canceled.Please create a new subscription to keep uninterrupted access.',
  FREE_TRIAL_ENDED: 'Your Free Trial Has Ended. Please contact your administrator.',
  USER_BLOCKED: 'User is blocked. Ask your clinic admin to unblock.',
  MD_TOOLBOX_CONFIG_MISSING:
    'MD Toolbox configuration is missing. Please add App Name, Practice ID, and MD Toolbox Key in Settings > Clinic Config > MD Toolbox.',
  _EXIST: (key) => `${key} already exists`,
  _REQUIRED: (key) => `${key} required`,
};
module.exports = {
  errorMessages,
};
