const objectiveIntervention = [
    {
      name: 'I1',
      objectiveId: 1,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I2',
      objectiveId: 1,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I3',
      objectiveId: 2,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I4',
      objectiveId: 2,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I5',
      objectiveId: 3,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I6',
      objectiveId: 3,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I7',
      objectiveId: 4,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I8',
      objectiveId: 4,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I9',
      objectiveId: 5,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I10',
      objectiveId: 5,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I11',
      objectiveId: 6,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I12',
      objectiveId: 6,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I13',
      objectiveId: 7,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I14',
      objectiveId: 7,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I15',
      objectiveId: 8,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I16',
      objectiveId: 8,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I17',
      objectiveId: 9,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I18',
      objectiveId: 9,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I19',
      objectiveId: 10,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I20',
      objectiveId: 10,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I21',
      objectiveId: 11,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I22',
      objectiveId: 11,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I23',
      objectiveId: 12,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I24',
      objectiveId: 12,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I25',
      objectiveId: 13,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I26',
      objectiveId: 13,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I27',
      objectiveId: 14,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I28',
      objectiveId: 14,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I29',
      objectiveId: 15,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I30',
      objectiveId: 15,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I31',
      objectiveId: 16,
      isDeleted: false,
      isActive: true,
    },
    {
      name: 'I32',
      objectiveId: 16,
      isDeleted: false,
      isActive: true,
    },
  ];
  
  module.exports = {
    objectiveIntervention,
  };
  